version: "3.8"
services:
  manga_image_translator:
    build:
      context: .
    container_name: manga_image_translator
    command: python -u /app/translate_demo.py --target-lang=ENG --manga2eng --verbose --log-web --mode web --use-inpainting --use-cuda --host=0.0.0.0 --port=5003
    volumes:
      - ./translate_demo.py:/app/translate_demo.py
      - ./web_main.py:/app/web_main.py
      - ./result:/app/result
    ports:
      - 5003:5003
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]