blank_issues_enabled: false
contact_links:
  - name: Manga Image Translator Community Support
    url: "https://github.com/zyddnys/manga-image-translator"
    about: Please ask and answer questions here.
